CREATE TABLE books (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    publishing_date DATE NOT NULL,
    title VARCHAR(255) NOT NULL,
    version INT(6),
    pages INT(6),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blogpost (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    publishing_date DATE NOT NULL,
    title VARCHAR(255) NOT NULL,
    version INT(6),
    url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE author (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    version INT(6),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
