= Install with Maven
keywords: stream, jpastreamer, java, maven
author: Per Minborg
:reftext: Install with Maven
:navtitle: Install with Maven
:source-highlighter: highlight.js

Since JPAStreamer acts merely as an API extension for any existing JPA provider it requires minimal installation and configuration efforts. You only need to specify that the JPAStreamer dependency is required to compile your source code.

NOTE: JPAStreamer requires use of Java 8 or later.

To install, add the following JPAStreamer dependency to the project's pom.xml-file:

[source, xml]
----
<dependencies>
    <dependency>
        <groupId>com.speedment.jpastreamer</groupId>
        <artifactId>jpastreamer-core</artifactId>
        <version>${jpa-streamer-version}</version>
    </dependency>
</dependencies>
----

== Multiple Source Directories
In some cases, the metamodel generated by JPAstreamer is not automatically detected by the compiler as source code. This can be fixed by explicitly pointing to the generated sources using the Maven Build Helper:

[source, xml]
----
 <plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>build-helper-maven-plugin</artifactId>
    <version>3.2.0</version>
    <executions>
        <execution>
            <phase>generate-sources</phase>
            <goals>
                <goal>add-source</goal>
            </goals>
            <configuration>
                <sources>
                    <source>target/generated-sources/annotations</source>#<1>
                </sources>
            </configuration>
        </execution>
    </executions>
</plugin>
----
<1> Path to the metamodel generated by JPAstreamer
