= Install with Gradle
keywords: stream, jpastreamer, java, gradle
author: Per Minborg
:reftext: Install with Gradle
:navtitle: Install with Gradle
:source-highlighter: highlight.js

Since JPAStreamer acts merely as an API extension for any existing JPA provider it requires minimal installation and configuration efforts. You only need to specify that the JPAStreamer dependency is required to compile your source code.

NOTE: JPAStreamer requires use of Java 8 or later.

To install, add the following JPAStreamer dependency to the project's build.gradle-file:

[source, text]
----
repositories {
	mavenCentral()
}

dependencies {
    compile "com.speedment.jpastreamer:jpastreamer-core:version"
    annotationProcessor "com.speedment.jpastreamer:fieldgenerator-standard:version"
}
----

== Multiple Source Directories
In some cases, the metamodel generated by JPAstreamer is not automatically detected by the compiler as source code. This can be fixed by pointing to an additional source directory in the Gradle build:

[source, text]
----
sourceSets {
    main {
        java {
            srcDir 'src/main/java'
            srcDir 'target/generated-sources/annotations'#<1>
        }
    }
}
----
<1> Path to the metamodel generated by JPAstreamer
