= What is a Stream?
keywords: stream, jpastreamer, java
author: Per Minborg
:reftext: What is a Stream?
:navtitle: What is a Stream?
:source-highlighter: highlight.js

JPA Streamer is all about Java 8 Streams, that allows you to process data in a declarative way similar to SQL statements. So if you are not familiar with the concept of `Streams`, I encourage you to read this chapter carefully. If you consider yourself a `Stream` expert, feel free to skip directly to the next chapter.

A Java 8 `Stream` is an `interface` with implementations that supports a functional style operation on streams of elements. The entire Java Collection framework was retrofitted with `Stream` support in Java 8.

Streams can be used to express a kind of "recipe" style of operations, allowing us to compose a number of function and only when the `Stream` is started, the functions are applied to the elements in the `Stream`. This means that `Streams` can be very efficient and general. A `Stream` recipe says *what to do* but generally *not how to do it* which is good from an abstraction point of view.

Consider the following simple example:

[source, java]
----
Stream.of( #<1>
        "Zlatan",
        "Tim",
        "Bo",
        "George",
        "Adam",
        "Oscar"
        )
        .filter(n -> n.length() > 2) #<2>
        .sorted() #<3>
        .collect(Collectors.toList()); #<4>
----
<1> Creates a `Stream` with the given content
<2> Retains only those `Strings` that are longer than 2 characters (i.e. "Bo" is dropped)
<3> Sorts the remaining `Strings` in natural order
<4> Collects the remaining sorted `Strings` in a `List`

Start by creating a Stream using the statement Stream.of(). Note that nothing happens with the Stream at this point. This yields a Stream which can be used to further build a “recipe” around. By adding a filter only Strings that are longer than 2 characters will be included. Again, the Stream is not started, this only tells the Stream that when it starts, the Strings should be filtered. Next, a sorted() operation is added to the Stream recipe. This means that when the Stream is started, all Strings that passes the filter shall be sorted in natural order. Again, nothing is flowing through the Stream, the Stream recipe (the stream recipe can more formally be called a stream pipeline) now holds yet an operation. The last operation to be added is collect.

This operation is different to all the previous operations in the way that it is a Terminal operation. Whenever a Terminal operation is applied to a Stream, the Stream cannot accept additional operations to its pipeline. It also means that the Stream is started.

It shall be noted that elements in a Stream are pulled by the Terminal Operation (i.e. the collect operation) and not pushed by the stream source. So, Collect will ask for the first element and that request will traverse up to the stream source that will provide the first element “Zlatan”. The filter operation will check if the length of “Zlatan” is greater than two (which it is) and will then propagate “Zlatan” to the sorted operation. Because the sorted operation needs to see all strings before it can decide on its output order, it will ask the stream source for all its remaining elements which, via the filter, is sent down the stream. Once all strings are received by the sorted operator, it will sort the strings and then output its first element (i.e. “Adam”) to the collect operation. The result of the entire stream statement will thus be:

[source]
----
"Adam", "George", "Oscar", "Tim", "Zlatan"
----

== Streams with JpaStreamer
With JPAStreamer, it is possible to use exactly the same semantics as for Java 8 streams. Instead of Strings as shown in the example above, database rows can be streamed. This way, database tables can be viewed as pure Java 8 Streams as shown hereunder:

[source, java]
----
users.stream() #<1>
    .map(u -> u.getName()) #<2>
    .filter(n -> n.length() > 2) #<3>
    .sorted() #<4>
    .collect(Collectors.toList()); #<5>
----
<1> Creates a `Stream` with users from a database
<2> Extract the name (a `String) from a user
<3> Retains only those `Strings` that are longer than 2 characters (i.e. "Bo" is dropped)
<4> Sorts the remaining `Strings` in natural order
<5> Collects the remaining sorted `Strings` in a `List

Since `Stream` is an interface, JPAStreamer can select from a variety of different implementations of a `Stream` depending on the pipeline that is used and other factors.

NOTE: The order in which elements are produced by the stream is unspecified and may change from one invocation to another. Because of that, it is an error to assume any particular order. Use the intermediate operation `sorted(Comparator)` if you need a certain element order.
