/*
 *
 * Copyright (c) 2006-2020, Speedment, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); You may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.speedment.jpastreamer.field;

import com.speedment.jpastreamer.field.trait.HasAttributeConverterClass;
import com.speedment.jpastreamer.field.trait.HasComparableOperators;
import com.speedment.runtime.compute.ToShort;
import com.speedment.jpastreamer.field.comparator.ShortFieldComparator;
import com.speedment.jpastreamer.field.internal.ShortFieldImpl;
import com.speedment.jpastreamer.field.method.ShortGetter;
import com.speedment.jpastreamer.field.trait.HasShortValue;

import javax.persistence.AttributeConverter;

/**
 * A field that represents a primitive {@code short} value.
 * <p>
 * Generated by com.speedment.sources.pattern.FieldPattern.
 * 
 * @param <ENTITY> entity type
 * @param <D>      database type
 * 
 * @author Emil Forslund
 * @since  3.0.0
 */
public interface ShortField<ENTITY, D> extends
        Field<ENTITY>,
        HasShortValue<ENTITY, D>,
        HasComparableOperators<ENTITY, Short>,
        ToShort<ENTITY>,
        ShortFieldComparator<ENTITY, D>,
        HasAttributeConverterClass<Short, D>
{
    
    /**
     * Creates a new {@link ShortField} using the default implementation.
     * 
     * @param <ENTITY>   entity type
     * @param <D>        database type
     * @param table      the table that this field belongs to
     * @param columnName the name of the database column the field represents
     * @param getter     method reference to getter in entity
     * @param attributeConverterClass the attribute converter class
     * @param unique     if column only contains unique values
     * @return           the created field
     */
    static <ENTITY, D> ShortField<ENTITY, D> create(
            Class<ENTITY> table,
            String columnName,
            ShortGetter<ENTITY> getter,
            Class<? extends AttributeConverter<Short, ? super D>> attributeConverterClass,
            boolean unique) {
        return new ShortFieldImpl<>(
                table, columnName, getter, attributeConverterClass, unique
        );
    }
    
    @Override
    default short applyAsShort(ENTITY entity) {
        return getAsShort(entity);
    }
    
    @Override
    ShortFieldComparator<ENTITY, D> comparator();
    
    @Override
    default ShortFieldComparator<ENTITY, D> reversed() {
        return comparator().reversed();
    }
    
    @Override
    default ShortField<ENTITY, D> getField() {
        return this;
    }
}