= Quick Start with JPAStreamer
keywords: stream, jpastreamer, java
author: Julia Gustafsson
:reftext: Quick Start
:navtitle: Quick Start with JPAStreamer
:source-highlighter: highlight.js
This section helps you get started with JPAStreamer in a few minutes. The process can be summed up in three steps:

. <<Installing JPAStreamer>>
. <<Build Your Project to Generate Fields>>
. <<Initiate JPAStreamer>>

NOTE: Use of JPAStreamer requires Java 8 or later.

NOTE: This guide assumes you are starting from an existing project that conveys to the standard JPA specification i.e. represent database tables as Entities etc.

== Installing JPAStreamer
The installation is performed by notifying your build tool that the JPAStreamer dependency is required to compile your source code. This is accomplished by using either of the following dependencies for Maven or Gradle.

=== Maven
Install JPAStreamer by adding the following dependency in the project's pom.xml-file:

[source, xml]
----
<dependencies>
    <dependency>
        <groupId>com.speedment.jpastreamer</groupId>
        <artifactId>core</artifactId>
        <version>${jpa-streamer-version}</version>
    </dependency>
</dependencies>
----

=== Gradle
Install JPAStreamer by adding the following dependency in the project's gradle.build-file:

[source, text]
----
repositories {
	mavenCentral()
}

dependencies {
    compile "com.speedment.jpastreamer:core:version"
    annotationProcessor "com.speedment.jpastreamer:fieldgenerator-standard:version"
}
----

== Build Your Project to Generate Fields
Once you have added the JPAStreamer dependency, go ahead and build your project to allow JPAStreamer to generate its required fields. The fields are generated into the target folder in the same package as the corresponding `Entity`.

NOTE: If you are running in an IDE, you may have to manually configure the output target folder as a source folder, or else the runtime compiler may not be aware of the generated classes.

== Initiate JPAStreamer
After installation, JPA Streamer is initialized with a simple builder. For JPAStreamer to know which database you would like to access, you need to provide the name of the persistence unit.

[source, java]
----
JPAStreamer jpaStreamer = JPAStreamer.createJPAStreamerBuilder("sakila") #<1>
            .build();
----
<1> "sakila" is to be replaced with the name of your persistence unit

To stream the entries of any table, simply call `jpaStreamer.stream()` and provide the class of the entity:

[source, java]
----
jpaStreamer.stream(Film.class) #<1>
    .forEach(System.out::println);
----
<1> `Film.class` refers to the annotated `Entity` that models the table which is to be streamed

To release any resources potentially held by JPA Streamer, simply close the streamer like so:

[source, java]
----
jpaStreamer.close();
----

== Next Steps
Now that you have access to JPAStreamer it's time to put the expressiveness of Java Streams to work. If you are not yet familiar with the `Stream` API, you may find our guide on xref:stream-fundamentals:stream_basics.adoc[Stream Fundamentals] helpful.

Otherwise, feel free to check out the large collection of examples of JPAStreamer usage.


